### ISSUE TITLE
Error message "active tab cannot be retrieved" should be cleared

### ISSUE THREAD

**Issue by Wikinaut** [rugk/offline-qr-code#144]
Example:
I want to create a QR code for the url of a downloadable file
https://grobox.de/tmp/briar-add-contacts-remotely-user-test.apk

QR code cannot be generated in this tab. When I manually paste the url as text inpout, the QR codeis generated, but thee warning message is still shown.

I suggest, you clear the warning message, when a text is manually entered.

Current workaround: open a new tab, create QR code for the empty tab, paste url as text to create QR code.

**Comment by rugk** [comment]
Oh, indeed. There are multiple issues though…

So I created some new ones:
* that no URL is actually got: https://github.com/rugk/offline-qr-code/issues/146
* broken image: https://github.com/rugk/offline-qr-code/issues/145 (do you also see that?)
* and this here, that it does not hide the error message.

**Comment by Wikinaut** [comment]
Hallo, das Problem ist die Fehlermeldung als solche - die ist diejenige, diestört. Sie liegt bei mir über dem QR code, so dass man - im besprochenen Fall - auch nicht einmal manuell den Text (im Textfeld) ändern kann.


Eine ausreichende Hilfe und Lösung des Problems wäre es aber, wenn der Fehlertext verschwände, sobald man im Textfeld etwas eintippt.

**Comment by rugk** [comment]
Genau dieses Verhalten sollte in https://github.com/rugk/offline-qr-code/commit/16a73882556bf46a5ab7df4477685198ab83bdf8 gefixt wurden sein, veröffentlicht als [v1.4](https://github.com/rugk/offline-qr-code/releases/tag/v1.4). Mit welcher Version funktioniert es bei dir immer noch nicht?

EN: This behavior should already be fixed with https://github.com/rugk/offline-qr-code/commit/16a73882556bf46a5ab7df4477685198ab83bdf8, released as  [v1.4](https://github.com/rugk/offline-qr-code/releases/tag/v1.4).
