### ISSUE TITLE
Updated translations for 'ru': Russian (Русский)

### ISSUE THREAD

**Issue by m1ndm1n3r** [rugk/offline-qr-code#217]
[wet_export.zip](https://github.com/rugk/offline-qr-code/files/3527733/wet_export.zip)

**Comment by rugk** [comment]
Thanks for your translation.
Feel free to create the same translation as a pull request (so you will be properly credited in the commit history), if you want. (If so, please adjust the indentation to two spaces. This is [a known issue](https://github.com/Lusito/web-ext-translator/issues/30).) Otherwise I'll soon do the PR by myself to get it merged.

Also notice there are more things to translate like the add-on listings on AMO etc. [See the contributing guide for more information.](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translation-style)

**Comment by rugk** [comment]
@m1ndm1n3r Still want to do it as a PR or shall I just manually merge it in the repo?

**Comment by m1ndm1n3r** [comment]
@rugk, please merge it by yourself
