### ISSUE TITLE
Insert the button into location bar

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [rugk/offline-qr-code#26]
Firefox allowed to insert a button at the right of location bar, so you can try to do it anyway.

**Comment by rugk** [comment]
Indeed, initially I just added in as a browser action (that's how that is [technically called](https://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/browser_action)) instead of a [an address bar button or so](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface), because that's Mozilla's recommendation for stuff you can do on every site.

However, I'd certainly like to offer the option to (also) put it into the address bar. The implementation work is likely not too hard, but it could be problematic that the add-on itself cannot hide the buttons (AFAIK), so the user would have to configure the display to move one button away or so.
And having two buttons for the same purpose when the add-on is initially installed is not a good (first) user experience.

**Comment by rugk** [comment]
Okay, maybe I am wrong, as it seems [the add-on can disable the action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/disable). :smiley:

**Comment by KrasnayaPloshchad** [comment]
This button also works on Android.

**Comment by rugk** [comment]
So I tried to implement this, but it does not look nice:
![grafik](https://user-images.githubusercontent.com/11966684/39397812-94bffcba-4b05-11e8-973f-4d5b8ce99eb6.png)

This is the state where the address bar (page action) is enabled, and the toolbar icon (browser action) is disabled.
As you can see, this looks weird. There are two/three problems:
* Neither the browser action, nor the page action can be completely hidden via JS/from the add-on. Only the user could do this. And as for the page action, not even the user can completly hide it, it will always be visible in the overflow menu:
   ![grafik](https://user-images.githubusercontent.com/11966684/39397903-d26ae9de-4b06-11e8-9217-8a93f53c7af5.png)
* The icon of the page action cannot be adjusted to the theme. That's why it looks so dark in the screenshot.
* The browser action icon looks awkward when disabled.

If you want to try it yourself, here is a patch file (I needed to rename it to txt, because of GitHub's upload restrictions):

[patch-pageAction.txt](https://github.com/rugk/offline-qr-code/files/1957847/patch-pageAction.txt)

Thus I am closing this issue. Unfortunately it is not possible in a sane way, currently.
