### ISSUE TITLE
The "like addon" tip is too aggressive/too often shown

### ISSUE THREAD

**Issue by vulpes9** [rugk/offline-qr-code#275]
## Steps to reproduce

1. Generate a code
2. dismiss tool-tip in pop-up
3. it happens again next time, or 2nd or 3rd

### Actual behavior

![grafik](https://user-images.githubusercontent.com/75497157/147415128-0c6a3dfe-bc9c-4df8-9963-7100bd7673fa.png)
![grafik](https://user-images.githubusercontent.com/75497157/147415213-21552f71-c2c4-4563-bf79-274585fe94f7.png)
![grafik](https://user-images.githubusercontent.com/75497157/147415396-ce590581-18d1-492d-8831-309e6c1772da.png)

The tool-tip will not stop.

### Expected behavior

I would like to see no more tool-tips at all.

## System

![grafik](https://user-images.githubusercontent.com/75497157/147415158-dc1a0b1c-b719-4521-8963-bcab78fcf278.png)

Operating system and version: 
Browser and version: Firefox 
Add-on version: 

![grafik](https://user-images.githubusercontent.com/75497157/147415145-bd5fceba-e023-46fd-9c30-bfa697273a32.png)
![grafik](https://user-images.githubusercontent.com/75497157/147415147-660cef16-80cf-4e36-8c6c-f1cdadc1df61.png)

## Possible solution

Please allow to disable tool-tips completely. It might be easier than writing code to memorize if they were already shown.
They are useful, but for advanced users they are a little repetitive and make me sad.

**Comment by rugk** [comment]
> It might be easier than writing code to memorize if they were already shown.

Actually

**Comment by vulpes9** [comment]
```
{
  "randomTips": {
    "tips": {
      "translateAddon": {
        "shownCount": 2,
        "dismissedCount": 1,
        "shownContext": {
          "popup": 2
        }
      },
      "androidQrReader": {
        "shownCount": 0,
        "dismissedCount": 0,
        "shownContext": {}
      },
      "likeAddon": {
        "shownCount": 36,
        "dismissedCount": 1,
        "shownContext": {
          "popup": 35,
          "options": 1
        }
      },
      "saveQr": {
        "shownCount": 8,
        "dismissedCount": 1,
        "shownContext": {
          "popup": 8
        }
      },
      "qrCodeHotkey": {
        "shownCount": 1,
        "dismissedCount": 1,
        "shownContext": {
          "popup": 1
        }
      }
    },
    "triggeredOpen": 69
  }
}
```

The "like addon" tool tip was show too aggressively, in agreement with your internal counters. I can only give you my word I dismissed it with X to close in the tip itself more than once. I think it needed a browser restart to show effect. I still see it sometimes like earlier today. But now it seems to have stopped.

**Comment by rugk** [comment]
Hi and thanks a lot for the data.

Yeah, according to the data, you only dismissed it one time and [it is supposed to be shown at max two times](https://github.com/rugk/offline-qr-code/blob/a0193ba1f1c5f90b06b6e99b9a5973b69d850e21/src/common/modules/data/Tips.js#L94), so well… it showed it 36 times, which I totally agree is way too aggressive… :upside_down_face: 

> If there is a flaw with your code (or my browser) the restart is what fixed it.

Yeah, I guess it is some caching bug, as the `AddonSettings` by default cache the settings.
Though [new settings should be saved to cache](https://github.com/TinyWebEx/AddonSettings/blob/7855b9dbeb6cbb8861f2d6b5ae916bd756f525ea/AddonSettings.js#L108-L113) and [we actually properly save the dismiss when it is triggered](https://github.com/TinyWebEx/RandomTips/blob/0eaaf040f21526edb424a40af3fd4c9cbadb3beb/RandomTips.js#L121), otherwise the one dismiss also would not have been saved.
However, the website the add-on loads is totally reloaded anyway when you open a popup.

Did you maybe mix the "dismissed in popup" and "dismissed on options page"? (Maybe even when having both open at the same time… :upside_down_face:) Or were all dismisses only on the popup page? (I mean the data shows it was shown at least once on the options page.)

--

> I didn't have the chance to close it yesterday as I was running a large file transfer.

However, when your settings are from your current browsing session, ~~the problem should still be there.~~ Ah, no `dismissedCount` is 1 and `requireDismiss` is 1, so it should never be shown again.
Hint: BTW, if you reset the options on the options page, all counters like these are also cleared (basically all data is cleared :upside_down_face:), so be aware of that (or, if you want to reproduce it, you can also do that deliberately of course).

So if it happens again, a copy of the console log would be very helpful. (again the context menu provides a "export -> to clipboard" option so you can copy everything with a proper formatting)

When you can reproduce it, it would be great to get the log from `about:debugging` again as described before. However to debug a popup [you need to disable popup hiding on click](https://extensionworkshop.com/documentation/develop/debugging/#debugging-popups) _before_ accessing the dev tools.
Note the sentence, so you may need to choose the correct HTML first (It is named `popup/qrcode.html` or so :upside_down_face:):
> click the page select icon (![grafik](https://user-images.githubusercontent.com/11966684/147594161-2a0b981a-f2bc-4265-866f-02d8c5d6f0fd.png)) to open the popup's document

**Comment by vulpes9** [comment]
I have given it some thought what actually went down here:

Considering that the last update was on Nov 20th, this is part of why I believe my Firefox ESR is part to blame. However, on the other end, when I tried to dismiss it again, it would poorly react without a reboot to me dismissing it. 

Your reply tells me the dismiss counter should be reading **2** by now, which it did not, and I am very sure I have dismissed it more than that.

>  Hint: BTW, if you reset the options on the options page, all counters like these are also cleared (basically all data is cleared 🙃), so be aware of that (or, if you want to reproduce it, you can also do that deliberately of course).
> 

I am willing to try that and see if the problem is reproducible. After all I don't like opening issues and then ghost the dev. 

Test done:
Okay I have dismissed it 8 out of 9 times and it still keeps showing. I doubt without a restart it will persist.

```
{
  "randomTips": {
    "tips": {
      "qrCodeHotkey": {
        "shownCount": 3,
        "dismissedCount": 0,
        "shownContext": {
          "popup": 3
        }
      },
      "translateAddon": {
        "shownCount": 0,
        "dismissedCount": 0,
        "shownContext": {}
      },
      "androidQrReader": {
        "shownCount": 0,
        "dismissedCount": 0,
        "shownContext": {}
      },
      "likeAddon": {
        "shownCount": 1,
        "dismissedCount": 0,
        "shownContext": {
          "popup": 1
        }
      },
      "saveQr": {
        "shownCount": 9,
        "dismissedCount": 1,
        "shownContext": {
          "popup": 9
        }
      }
    },
    "triggeredOpen": 15
  }
}
```

![grafik](https://user-images.githubusercontent.com/75497157/147610589-0bc56a4b-17c7-4cd9-b71e-2df6d9a2af12.png)

**Comment by 961028** [comment]
I also feel like they come up way too often, and I would rather not have them at all.

**Comment by vulpes9** [comment]
I guess this can be closed.

**Comment by rugk** [comment]
If you feel so. Also BTW the width is just the text-width it needs to display the tip, there is not a lot I can do, it has the width and takes it, as expected.

> You could perhaps disable them permanently after they have been shown 10 times, or add a tooltip: "Dismissing a tooltip will make it go away permanently".

The last thing is not actually true. [As explained before](https://github.com/rugk/offline-qr-code/issues/275#issuecomment-1001802344), in this case, it _must be dismissed_ at least once to be never shown again _and_ if it _has been dismissed twice or more_ it is shown again. (with the current settings)
The thing is to hide this complexity from the user and just provide unobtrusive, but contextually helpful tips.

For anyone else to debug thus, how to get the data I need is described in the post I already linked. Without that, this is hard to debug – by design, after all, as it is very "random" depending on many factors, that were included in the library.

**Comment by vulpes9** [comment]
> The thing is to hide this complexity from the user and just provide unobtrusive, but contextually helpful tips.

If that is your wish a small icon (maybe with a question mark) and a ```moz-extension://``` html page with further information about using/supporting/helping the addon would help better. Developers usually have different views than users. Many people remember "Karl Klammer" or "Clippy" from Word. For me tooltips usually have the opposite effect from negative conditioning.

I'd rate this addon 5 stars, it's amazing, but making an addons mozilla account just for that is unlikely. To explain my feelings about such a notification. Other developers show a pop-up tab after updates like Tampermonkey. I just find it hard to talk about this, since this is your addon and you run this show however you want. So I don't know if my opinions are helpful.
