### ISSUE TITLE
Use system clipboard content than tab url to gen code.

### ISSUE THREAD

**Issue by qrqhuang** [rugk/offline-qr-code#282]
I was commonly used clipboard content to generate code.
Try to give an option to choose.

**Comment by rugk** [comment]
Good idea. Note that this [would require a new permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard) for clipboard access likely, but that can be queried

## HowTo

I imagine a setting with a checkbox:
* [x] Use clipboard content when opening popup.

If you enable that, instead of [using the tab URL](https://github.com/rugk/offline-qr-code/blob/b15ecc86a4d386dbc08de868ea773c649b921ca1/src/popup/modules/InitQrCode.js#L78-L79) it should override it (if required also [possible with a message from the background script or so](https://github.com/rugk/offline-qr-code/blob/b15ecc86a4d386dbc08de868ea773c649b921ca1/src/popup/modules/ReceiveBackgroundMessages.js#L25) with the clipboard content.
If a permission is required, one can couple it in this extension [with the PermissionRequest](https://github.com/TinyWebEx/PermissionRequest) library (also used in other extensions, if one needs to get an example).

Important things:
* If the clipboard is empty, it should IMHO still fallback/use the website URL then as usual!
* If some text is selected and the option in the settings is enabled (as usual), this should take preference over the clipboard content IMHO.
  **Reasoning:** The thing is the clipboard is likely to contain outdated stuff, even passwords or so, which you have copied a quite long time ago, while a text selection on the website is _much_ less permanent (i.e. goes away fast when you have to interact in some other way with the site) _and_ selecting something may be a way more deliberate act than just copying sth. in another application even possibly or so.
  
That all said, I guess this is a good „good first issue“ thing if someone wants to really implement it. Note though, it may be not the easiest one, as one has to touch a few topics (settings, actual logic etc.) that are simplified due to the libs we use, but may still require some clever ideas or so.

**Comment by frooia** [comment]
New open source dev here, can I try this one?

**Comment by Ravina-Deogadkar** [comment]
Can I work on this?

**Comment by rugk** [comment]
Hi oh sorry for the delay, missed my notifications, yes you can both try. However, @Ravina-Deogadkar I just saw @frooia already did a PR in https://github.com/rugk/offline-qr-code/pull/286, so that is the base for implementation.

I thus will assign @frooia first, but if help is needed, of course I assume @Ravina-Deogadkar you can jump in and help here. Feel free to test or review the PR, BTW.

**Comment by rugk** [comment]
So @GrupaIMEX and  @Ravina-Deogadkar if you want to take over/finish the PR https://github.com/rugk/offline-qr-code/pull/286 feel free to do so. There should just be some minor work to do.

**Comment by BrandonTuTwo2** [comment]
Hello! is this issue still available if so may I?

**Comment by BrandonTuTwo2** [comment]
will do thanks!

**Comment by rugk** [comment]
Fixed by https://github.com/rugk/offline-qr-code/pull/337
