### ISSUE TITLE
Big applause for the "recreation" of a real offline-version!

### ISSUE THREAD

**Issue by Wikinaut** [rugk/offline-qr-code#29]
See subject.

**Comment by rugk** [comment]
Yeah, thanks! Praise is always appreciated. :smiley: 

As you maybe noticed, I also tried to make some other things better than some other add-ons… :wink: 

BTW my add-on still needs some votes on AMO, so if you like it, you can also vote for it.

**Comment by Wikinaut** [comment]
On debian 9, the Firefox version is at Firefox ESR 52.7.3 and the current offline-qr-code cannot be installed there. Just as info.

**Comment by rugk** [comment]
Yes, as stated in the Readme, I currently have set it to Firefox 57 and higher. If you want to test whether it also works in earlier versions (which would be great), you can, however, also clone the repo or use the XPI [remove that line](https://github.com/rugk/offline-qr-code/blob/b3dce735b986eac139fac23b596f173b252b216a/src/manifest.json#L47) and [load the add-on](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension#Installing) via `about:debugging` in Firefox.

**Comment by Wikinaut** [comment]
I tested this here with my debian 9 - works with FF ESR 52.7.3 see https://github.com/rugk/offline-qr-code/pull/33

**Comment by Wikinaut** [comment]
I tested this - but it is not working.

**Comment by rugk** [comment]
If you want you can send me the console output so I can have a look (on the same page that "debugging" button), but maybe it's not worth it, because in the future I may require even more recent versions of FF (see https://github.com/rugk/offline-qr-code/issues/31, which would require Firefox 60).

Anyway the goal of this add-on was not really backwards-compatibility. The ESR version of the new Quantum Firefox will soon be published anyway, so then anyone can use an up-to-date Firefox and this new extension. As for old Firefox'es there are still enough other QR code add-ons.

**Comment by rugk** [comment]
FYI Firefox 60 ESR has been released, so everything should be fine. :smile:
