### ISSUE TITLE
Encrypted exchange by QR-code channel

### ISSUE THREAD

**Issue by oneofthehorses** [rugk/offline-qr-code#315]
Hi!

It would be **awesome** feature to create something like "encrypted channel where devices first say hello to each other (wich means exchange of public keys) and then you can send\recive information by secure channel throught QR-code's

**Thanks** for your works!!!

**Comment by rugk** [comment]
Well… if we ask for security we first would have to ask for a threat model… What's yours?

I propose one here…

## treat model

Anyone intercepting/MITM the connection? I guess?
The situation could be scanning a password from your desktop with your phone.

Threats are many:
* compromised devices/apps etc. (note your app on your phone to scan it etc.)
* interception in between
* etc.

We focus on the interception part.

## current solution

IMHO the current solution is already quite robust, as “intercepting” currently would require:
* _physical presence_ (as long as your devices are not compromised, but we did not want to consider this), where someone could scan the code (as the data is not sent anywhere)
* _exact timing_ as you probably would close that QR code soon (however, a photo of it taken at the wrong moment would be enough) or the lightning etc. changes, so the code cannot be scanned anymore by the attacker
* _possibly be noticable_ as you may see when someone it behind you

All in all, practically, I only see [should surfing](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security)) as a practical attack. While photos may be possible to expand the time for an attack, it's likely also easy enough to scan the QR code instantly instead.

Note if you are being shoulder-surfed, possibly much more data is already compromised, as you are likely being watched for longer and people may see entering your password etc.

## Proposed solution

Some asymmetric(?) encryption.

However:
  * Note: Simply passing private and public keys is quite useless. If our shoulder surfer can intercept the private key, they can also easily decode the. And it is likely that they can intercept both…
 * Thus a [diffie hellman exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) or something similar would need to be implemented.

## Effects

* It would make a passive shoulder surfing attack an active MITM attack. Yes. Like, you need to intercept the QR code somehow and possibly prevent a forged QR code to MITM e.g. a [diffie hellman exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange). The reason is DH is vulnerable to MITM attacks.
  However, I see that this is likely hard for QR codes, as in our treat model you likely can only scan your "real" QR code due to the physical distance involved.

Thus, this could indeed be effective.

## Implementation effort

Here comes the catch: Huuuge. Especially to do properly. E.g. one big challenge is a [diffie hellman exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) would require _your phone_ communicating back to _your laptop_. Bidirectional communication is, however, not really a feature of QR codes. :wink: 
(Also said DH key exchange has _big_ key lengths, but this could be solved by using elliptic curves aka ECDH instead.)

However, the worst thing may be a practical one: Both clients need to support it. If this add-on supports it, that is not enough. _The app_ (in our example) also needs to do so.

## Summary

All in all, this is less benefit with _much_ work. And without a proper way to do it (cryptography always goes wrong and without being a cryptographer you ought not even to try to implement low-level stuff.), it will likely fail.
Thus, I don't see that as a feature soon or in the near future.

## Alternatives

* maybe saving asymmetric keys for longer on both clients: impractical, needs key management (yet more work), what happens on compromise?
* symmetric encryption: way easier to implement, but still suffers from the "both clients support" problem. Also you can use plenty of tools for that already and just then paste your encrypted data into the QR code generator.

**Comment by oneofthehorses** [comment]
The main idea behind this in sense of benefits is work with airgapped OS's and Live USB like Tails OS in case of passwords or any sensetive info compromised. 

This is kinda same realisation but in bit different angle (can check from 2:53) https://yewtu.be/watch?v=LfNoeu9s93Y

**Comment by rugk** [comment]
@oneofthehorses okay, hmm so some software called "QR bridge" implements something like this and the video author says it costs $19 on some (Apple app?) store? Thus it is likely proprietary and I would not trust it with _any_ sensitive data ion the first place.

I also found no good results for it. And the link in the description goes to https://sunknudsen.com/store/qr-bridge, which is a 404 page… so, well…

**Comment by oneofthehorses** [comment]
Yes, that's why i also **don't trust** him and any proprietary implimentation of if, so i taking time to find **foss** alternative

But yet, without success
